# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: API Interface

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test-api-interface:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.23']

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Display Go version
        run: go version

      - name: Set up working directory
        run: cd api-interface

      - name: Install dependencies
        run: |
          cd api-interface
          go get .

      - name: Build
        run: |
          cd api-interface
          go build -o app

      - name: Run tests
        run: |
          cd api-interface
          go test ./...
